server:
  port: 8080
  servlet:
    context-path: "/demo"
spring:
  profiles:
    active: dev
  application:
    name: springboot-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-demo?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://192.168.50.148:3306/user_test?useUnicode=true&characterEncoding=utf8
  redis:
    host: localhost
    port: 6379
    connect-timeout: 5000
    timeout: 3000
    lettuce:
      pool:
        max-active: 100 #最大连接数
        max-idle: 8 #最大空闲数
        max-wait: -1  #最大阻塞等待时间
        min-idle: 2 #最小空闲数
    sentinel:
      master: master
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    locale: zh_CN
logging:
#  level:
#    com:
#      springboot:
#        demo: debug
  config: classpath:logback-spring.xml
mybatis-plus:
  type-enums-package: com.springboot.demo
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
